AWSTemplateFormatVersion: 2010-09-09

Resources:

  #Create the VPC with Cidr block 10.0.0.0/16
  VPC:
    Type: 'AWS::EC2::VPC'
    properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        -Key: Name
         Value: !Join
          - ''
          - - !Ref 'AWS::StackName'
           -  '-VPC'

  
  